import { readFile, readdir, writeFile } from "node:fs/promises";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const websiteDirectory = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const workspaceDirectory = resolve(websiteDirectory, "../..");
const outputPath = join(websiteDirectory, "src/generated/docs.ts");

async function readEntries(directory, kind) {
  const absoluteDirectory = join(workspaceDirectory, directory);
  const names = (await readdir(absoluteDirectory, { withFileTypes: true }))
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort();

  return Promise.all(
    names.map(async (directoryName) => {
      const entryDirectory = join(absoluteDirectory, directoryName);
      const packageJson = JSON.parse(
        await readFile(join(entryDirectory, "package.json"), "utf8"),
      );
      const markdown = await readFile(join(entryDirectory, "README.md"), "utf8");
      const shortName =
        kind === "provider"
          ? directoryName.replace(/^provider-/u, "")
          : directoryName;

      return {
        description: packageJson.description,
        kind,
        markdown,
        name: packageJson.name,
        shortName,
        source: relative(workspaceDirectory, join(entryDirectory, "README.md")),
        url:
          kind === "provider"
            ? `/docs/providers/${shortName}`
            : `/docs/${shortName}`,
      };
    }),
  );
}

const docs = [
  ...(await readEntries("packages", "package")),
  ...(await readEntries("providers", "provider")),
];

const source = `// Generated by scripts/generate-docs.mjs. Do not edit.
export type DocKind = "package" | "provider";

export interface DocEntry {
  readonly description: string;
  readonly kind: DocKind;
  readonly markdown: string;
  readonly name: string;
  readonly shortName: string;
  readonly source: string;
  readonly url: string;
}

export const docs = ${JSON.stringify(docs, null, 2)} as const satisfies readonly DocEntry[];
`;

if (process.argv.includes("--check")) {
  const existing = await readFile(outputPath, "utf8").catch(() => "");
  if (existing !== source) {
    console.error("Generated documentation is out of date. Run pnpm docs:generate.");
    process.exitCode = 1;
  }
} else {
  await writeFile(outputPath, source);
  console.log(`Generated ${docs.length} documentation entries.`);
}
